
-- ==========================================
-- HOTEL SAI NANDADEEP DATABASE SCHEMA
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/cdotyptpcevrbnyyuypx/sql/new
-- ==========================================

-- 1. Create Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  mobile_number TEXT NOT NULL,
  address TEXT NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  rooms_count INT NOT NULL,
  room_type TEXT NOT NULL,
  total_price NUMERIC NOT NULL,
  payment_method TEXT NOT NULL,
  transaction_id TEXT NOT NULL UNIQUE,
  floor TEXT,
  room_numbers TEXT
);

-- 2. Create Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  author TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content TEXT NOT NULL,
  avatar TEXT
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- 4. Create Security Policies
-- Allow public to insert bookings
CREATE POLICY "Enable insert for all users" ON public.bookings 
FOR INSERT WITH CHECK (true);

-- Allow public to read reviews
CREATE POLICY "Enable read access for all users" ON public.reviews 
FOR SELECT USING (true);

-- Allow public to submit a review
CREATE POLICY "Enable insert access for all users" ON public.reviews 
FOR INSERT WITH CHECK (true);
